"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from "react";

type Source = "Instagram" | "Facebook" | "YouTube" | "Other";
type Status = "available" | "unavailable";
type Video = { id:string; title:string; url:string; category:string; subcategory:string; tags:string[]; notes:string; favorite:boolean; source:Source; addedAt:string; status:Status; categoryLocked:boolean; tagsLocked:boolean; aiStatus:"pending"|"done"|"failed" };
type VideoForm = { title:string; url:string; category:string; subcategory:string; tags:string; notes:string; status:Status };
type Category = { id:string; name:string; subcategories:string[] };

const STORAGE_KEY="recipe-reel-library:v1", CATEGORY_KEY="video-library:categories:v1";
const URL_REGEX=/https?:\/\/(?:www\.)?(?:instagram\.com\/(?:reel|reels|p)\/[^\s<>]+|facebook\.com\/(?:reel|watch|share\/(?:r|v))\/[^\s<>]+|fb\.watch\/[^\s<>]+|youtube\.com\/(?:shorts\/[^\s<>]+|watch\?[^\s<>]+)|youtu\.be\/[^\s<>]+)/gi;
const DEFAULT_CATEGORIES:Category[]=[
  {id:"food",name:"Food",subcategories:["Breakfast","Entree","Snacks","Drinks","Dessert","Sides","Soups & Salads"]},
  {id:"travel",name:"Travel",subcategories:["Places","Travel Tips","Hotels & Stays"]},
  {id:"gardening",name:"Gardening",subcategories:["Plants","Landscaping","Gardening Tips"]},
  {id:"life",name:"Life Lessons",subcategories:["Motivation","Relationships","Spiritual"]},
  {id:"other",name:"Other",subcategories:[]},{id:"uncategorized",name:"Uncategorized",subcategories:[]}
];
const EMPTY_FORM:VideoForm={title:"",url:"",category:"Uncategorized",subcategory:"",tags:"",notes:"",status:"available"};

function cleanUrl(url:string){return url.replace(/[)>\],.!?]+$/,"")}
function canonicalUrl(raw:string){try{const u=new URL(cleanUrl(raw));u.hostname=u.hostname.replace(/^www\./,"").toLowerCase();u.hash="";["igsh","igshid","mibextid","utm_source","utm_medium","utm_campaign","utm_content","si","feature"].forEach(k=>u.searchParams.delete(k));u.searchParams.sort();if(u.hostname==="instagram.com")u.pathname=u.pathname.replace(/^\/reels\//,"/reel/");u.pathname=u.pathname.replace(/\/$/,"");return u.toString().replace(/\?$/,"")}catch{return cleanUrl(raw).toLowerCase()}}
function sourceFor(url:string):Source{if(url.includes("instagram.com"))return"Instagram";if(url.includes("facebook.com")||url.includes("fb.watch"))return"Facebook";if(url.includes("youtube.com")||url.includes("youtu.be"))return"YouTube";return"Other"}
function dateFromLine(line:string){const candidates=[line.match(/^\[([^\]]+)\]/)?.[1],line.match(/^(\d{1,2}\/\d{1,2}\/\d{2,4},?\s+\d{1,2}:\d{2}(?::\d{2})?\s*(?:AM|PM)?)/i)?.[1]].filter(Boolean) as string[];for(const value of candidates){const parsed=new Date(value.replace(/\u202f/g," "));if(!Number.isNaN(parsed.getTime()))return parsed.toISOString()}return new Date().toISOString()}
function extractVideos(text:string,existing:Video[]){const seen=new Set(existing.map(v=>canonicalUrl(v.url)));return[...text.matchAll(URL_REGEX)].flatMap((match,index)=>{const url=cleanUrl(match[0]),key=canonicalUrl(url);if(seen.has(key))return[];seen.add(key);const start=text.lastIndexOf("\n",match.index??0)+1,end=text.indexOf("\n",match.index??0),line=text.slice(start,end===-1?undefined:end),label=line.slice(0,line.indexOf(match[0])).replace(/^.*? - (?:You|Me):\s*/i,"").replace(/^\[[^\]]+\]\s*[^:]+:\s*/,"").trim(),source=sourceFor(url);return[{id:crypto.randomUUID(),title:label||`${source} video ${existing.length+index+1}`,url,category:"Uncategorized",subcategory:"",tags:[],notes:label,favorite:false,source,addedAt:dateFromLine(line),status:"available" as Status,categoryLocked:false,tagsLocked:false,aiStatus:"pending" as const}]})}
function normalizeStoredVideos(items:Partial<Video>[]){const foodSubs=DEFAULT_CATEGORIES[0].subcategories;return items.map(v=>{const legacyFood=foodSubs.includes(v.category??""),resolvedCategory=legacyFood?"Food":v.category??"Uncategorized",resolvedTags=v.tags??[];return({...v,category:resolvedCategory,subcategory:legacyFood?v.category??"":v.subcategory??"",tags:resolvedTags,status:v.status??"available",addedAt:v.addedAt??new Date().toISOString(),categoryLocked:v.categoryLocked??resolvedCategory!=="Uncategorized",tagsLocked:v.tagsLocked??resolvedTags.length>0,aiStatus:v.aiStatus??"done"}) as Video})}
function youtubeId(raw:string){try{const u=new URL(raw);if(u.hostname.includes("youtu.be"))return u.pathname.split("/").filter(Boolean)[0];if(u.pathname.startsWith("/shorts/"))return u.pathname.split("/")[2];return u.searchParams.get("v")}catch{return null}}
function embedUrl(video:Video){if(video.source==="YouTube"){const id=youtubeId(video.url);return id?`https://www.youtube.com/embed/${id}?autoplay=1&rel=0`:null}if(video.source==="Instagram"){try{const u=new URL(video.url),p=u.pathname.split("/").filter(Boolean);return p[1]?`https://www.instagram.com/reel/${p[1]}/embed/`:null}catch{return null}}if(video.source==="Facebook")return`https://www.facebook.com/plugins/video.php?href=${encodeURIComponent(video.url)}&show_text=false&autoplay=true&width=500`;return null}

function InstagramEmbed({url,title}:{url:string;title:string}){
  const[html,setHtml]=useState(""),[ready,setReady]=useState(false);const containerRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{let active=true;setReady(false);fetch(`/api/embed?url=${encodeURIComponent(url)}`).then(r=>r.ok?r.json():Promise.reject()).then((data:{html?:string})=>{if(active&&data.html)setHtml(data.html)}).catch(()=>{if(active)setHtml("")});return()=>{active=false}},[url]);
  useEffect(()=>{if(!html)return;const process=()=>{const api=(window as Window&{instgrm?:{Embeds:{process:()=>void}}}).instgrm;if(api){api.Embeds.process()}};const markReady=()=>{if(containerRef.current?.querySelector("iframe"))setReady(true)};const observer=new MutationObserver(markReady);if(containerRef.current)observer.observe(containerRef.current,{childList:true,subtree:true});const existing=document.querySelector<HTMLScriptElement>('script[src="https://www.instagram.com/embed.js"]');if((window as Window&{instgrm?:unknown}).instgrm){process()}else if(existing){existing.addEventListener("load",process,{once:true})}else{const script=document.createElement("script");script.async=true;script.src="https://www.instagram.com/embed.js";script.addEventListener("load",process,{once:true});document.body.appendChild(script)}const retry=window.setTimeout(()=>{process();markReady()},500);return()=>{observer.disconnect();window.clearTimeout(retry);existing?.removeEventListener("load",process)}},[html]);
  return <div ref={containerRef} className={`instagram-player ${ready?"ready":"processing"}`} aria-label={title}>{html?<div dangerouslySetInnerHTML={{__html:html}}/>:<div className="embed-loading">Loading Instagram video…</div>}{html&&!ready?<div className="embed-shield">Preparing inline player…</div>:null}</div>
}

function VideoCard({video,playing,onPlay,onEdit,onDelete,onFavorite,onStatus}:{video:Video;playing:boolean;onPlay:()=>void;onEdit:()=>void;onDelete:()=>void;onFavorite:()=>void;onStatus:()=>void}){
  const[thumbnail,setThumbnail]=useState<string|null>(null),[failed,setFailed]=useState(false);
  useEffect(()=>{let active=true;setThumbnail(null);setFailed(false);fetch(`/api/thumbnail?url=${encodeURIComponent(video.url)}`).then(r=>r.ok?r.json():Promise.reject()).then((d:{thumbnail?:string})=>{if(active&&d.thumbnail)setThumbnail(d.thumbnail)}).catch(()=>{if(active)setFailed(true)});return()=>{active=false}},[video.url]);
  const player=embedUrl(video),unavailable=video.status==="unavailable";
  return <article className={`recipe-card ${unavailable?"unavailable":""}`}><div className={`source-badge ${video.source.toLowerCase()}`}>{video.source}</div><button className={`heart ${video.favorite?"active":""}`} onClick={onFavorite}>♥</button>
    {unavailable?<div className="not-available"><span>Video not available</span><small>Removed, private, or no longer accessible</small></div>:playing&&video.source==="Instagram"?<InstagramEmbed url={video.url} title={video.title}/>:playing&&player?<div className="inline-player"><iframe src={player} title={video.title} allow="autoplay; encrypted-media; picture-in-picture; web-share" allowFullScreen/></div>:<button className="reel-art" onClick={onPlay} aria-label={`Play ${video.title}`}>{thumbnail&&!failed?<img src={thumbnail} alt="" onError={()=>setFailed(true)}/>:<span className="plate">{video.category==="Travel"?"✈️":video.category==="Gardening"?"🌿":video.category==="Life Lessons"?"💡":video.category==="Food"?"🍲":"🎬"}</span>}<span className="play">▶</span></button>}
    <div className="card-body"><p className="eyebrow">{video.category}{video.subcategory?` · ${video.subcategory}`:""}</p><h2>{video.title}</h2><p className="saved-date">Saved {new Date(video.addedAt).toLocaleString()}</p>{video.tags.length?<div className="tags">{video.tags.map(t=><span key={t}>{t}</span>)}</div>:null}{video.notes?<p className="notes">{video.notes}</p>:<p className="notes muted">Add a note about this video.</p>}<div className="card-actions"><a href={video.url} target="_blank" rel="noreferrer" className="watch">Open original ↗</a><button onClick={onEdit}>Edit</button><button onClick={onStatus}>{unavailable?"Restore":"Mark unavailable"}</button><button className="delete" onClick={onDelete}>Delete</button></div></div></article>
}

export default function Home(){
  const[videos,setVideos]=useState<Video[]>([]),[categories,setCategories]=useState<Category[]>(DEFAULT_CATEGORIES),[ready,setReady]=useState(false),[query,setQuery]=useState(""),[category,setCategory]=useState("All"),[expandedCategory,setExpandedCategory]=useState(""),[subcategory,setSubcategory]=useState(""),[favorites,setFavorites]=useState(false),[showArchive,setShowArchive]=useState(false),[form,setForm]=useState<VideoForm>(EMPTY_FORM),[editingId,setEditingId]=useState<string|null>(null),[dialogOpen,setDialogOpen]=useState(false),[managerOpen,setManagerOpen]=useState(false),[newCategory,setNewCategory]=useState(""),[newSubs,setNewSubs]=useState<Record<string,string>>({}),[playingId,setPlayingId]=useState<string|null>(null),[aiRunning,setAiRunning]=useState(false),[toast,setToast]=useState("");const fileRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{let active=true;(async()=>{let localVideos:Video[]=[],localCategories:Category[]=DEFAULT_CATEGORIES;try{const saved=localStorage.getItem(STORAGE_KEY),savedCats=localStorage.getItem(CATEGORY_KEY);if(saved)localVideos=normalizeStoredVideos(JSON.parse(saved));if(savedCats)localCategories=JSON.parse(savedCats)}catch{}try{const response=await fetch("/api/library",{cache:"no-store"});if(response.status===401){location.href="/sign-in";return}if(!response.ok)throw new Error();const result=await response.json() as {exists:boolean;data?:{videos?:Partial<Video>[];categories?:Category[]}};if(!active)return;if(result.exists&&result.data){setVideos(normalizeStoredVideos(result.data.videos??[]));setCategories(result.data.categories?.length?result.data.categories:DEFAULT_CATEGORIES)}else{setVideos(localVideos);setCategories(localCategories);if(localVideos.length||localCategories.length)await fetch("/api/library",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({videos:localVideos,categories:localCategories})})}}catch{if(active){setVideos(localVideos);setCategories(localCategories);setToast("Database unavailable—using the local cache")}}finally{if(active)setReady(true)}})();return()=>{active=false}},[]);
  useEffect(()=>{if(!ready)return;localStorage.setItem(STORAGE_KEY,JSON.stringify(videos));localStorage.setItem(CATEGORY_KEY,JSON.stringify(categories));const timer=window.setTimeout(()=>{fetch("/api/library",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({videos,categories})}).then(response=>{if(response.status===401)location.href="/sign-in"}).catch(()=>{})},500);return()=>window.clearTimeout(timer)},[videos,categories,ready]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),3200);return()=>clearTimeout(t)},[toast]);
  const formSubs=categories.find(c=>c.name===form.category)?.subcategories??[],filtered=useMemo(()=>{const q=query.toLowerCase().trim();return videos.filter(v=>(showArchive?v.status==="unavailable":v.status==="available")&&(!q||[v.title,v.category,v.subcategory,v.notes,...v.tags].join(" ").toLowerCase().includes(q))&&(category==="All"||v.category===category)&&(!subcategory||v.subcategory===subcategory)&&(!favorites||v.favorite)).sort((a,b)=>new Date(b.addedAt).getTime()-new Date(a.addedAt).getTime())},[videos,query,category,subcategory,favorites,showArchive]);
  const chooseCategory=(name:string)=>{setCategory(name);setExpandedCategory(current=>name==="All"?"":current===name?"":name);setSubcategory("");setFavorites(false);setShowArchive(false);setPlayingId(null)},openNew=()=>{setEditingId(null);setForm(EMPTY_FORM);setDialogOpen(true)},openEdit=(v:Video)=>{setEditingId(v.id);setForm({title:v.title,url:v.url,category:v.category,subcategory:v.subcategory,tags:v.tags.join(", "),notes:v.notes,status:v.status});setDialogOpen(true)};
  function saveVideo(e:FormEvent){e.preventDefault();const url=cleanUrl(form.url.trim()),tags=form.tags.split(",").map(t=>t.trim()).filter(Boolean);if(editingId){setVideos(a=>a.map(v=>v.id===editingId?{...v,...form,url,tags,source:sourceFor(url),categoryLocked:true,tagsLocked:true}:v));setToast("Video updated and manual choices locked")}else{if(videos.some(v=>canonicalUrl(v.url)===canonicalUrl(url))){setToast("That video is already in your library");return}setVideos(a=>[{id:crypto.randomUUID(),...form,url,tags,source:sourceFor(url),favorite:false,addedAt:new Date().toISOString(),categoryLocked:true,tagsLocked:true,aiStatus:"done"},...a]);setToast("Video added")}setDialogOpen(false)}
  async function autoCategorize(items:Video[]){const eligible=items.filter(v=>!v.categoryLocked||!v.tagsLocked);if(!eligible.length)return;setAiRunning(true);let completed=0;for(const video of eligible){try{const response=await fetch("/api/classify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({video:{url:video.url,title:video.title,notes:video.notes},categories})});if(!response.ok)throw new Error();const suggestion=await response.json() as {title?:string;description?:string;category:string;subcategory:string;tags:string[]};setVideos(current=>current.map(item=>item.id===video.id?{...item,title:item.title||suggestion.title||item.title,notes:item.notes||suggestion.description||item.notes,category:item.categoryLocked?item.category:suggestion.category,subcategory:item.categoryLocked?item.subcategory:suggestion.subcategory,tags:item.tagsLocked?item.tags:suggestion.tags,aiStatus:"done"}:item));completed++}catch{setVideos(current=>current.map(item=>item.id===video.id?{...item,aiStatus:"failed"}:item))}}setAiRunning(false);setToast(completed?`AI organized ${completed} videos`:"AI organizing is unavailable. Check the API key.")}
  async function importFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{if(file.name.toLowerCase().endsWith(".json")){const seen=new Set(videos.map(v=>canonicalUrl(v.url))),unique=(JSON.parse(await file.text()) as Video[]).filter(v=>v.url&&!seen.has(canonicalUrl(v.url))).map(v=>({...v,subcategory:v.subcategory??"",status:v.status??"available" as Status,categoryLocked:v.categoryLocked??true,tagsLocked:v.tagsLocked??true,aiStatus:v.aiStatus??"done" as const}));setVideos(a=>[...unique,...a]);setToast(`Imported ${unique.length} videos from backup`)}else{const added=extractVideos(await file.text(),videos);setVideos(a=>[...added,...a]);setToast(added.length?`Imported ${added.length} new links. Organizing…`:"No new links—duplicates and prior corrections were preserved");if(added.length)void autoCategorize(added)} }catch{setToast("Could not read that file")}e.target.value=""}
  function exportBackup(){const blob=new Blob([JSON.stringify(videos,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`saved-video-library-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
  function addCategory(){const name=newCategory.trim();if(!name||categories.some(c=>c.name.toLowerCase()===name.toLowerCase()))return;setCategories(a=>[...a.slice(0,-1),{id:crypto.randomUUID(),name,subcategories:[]},a.at(-1)!]);setNewCategory("")}
  function renameCategory(id:string,name:string){const old=categories.find(c=>c.id===id)?.name;if(!old||!name.trim())return;setCategories(a=>a.map(c=>c.id===id?{...c,name:name.trim()}:c));setVideos(a=>a.map(v=>v.category===old?{...v,category:name.trim()}:v));if(category===old)setCategory(name.trim())}
  function deleteCategory(id:string){const c=categories.find(x=>x.id===id);if(!c||c.name==="Uncategorized"||!confirm(`Delete ${c.name}? Its videos will move to Uncategorized.`))return;setCategories(a=>a.filter(x=>x.id!==id));setVideos(a=>a.map(v=>v.category===c.name?{...v,category:"Uncategorized",subcategory:""}:v));chooseCategory("All")}
  function addSub(id:string){const value=(newSubs[id]??"").trim();if(!value)return;setCategories(a=>a.map(c=>c.id===id&&!c.subcategories.includes(value)?{...c,subcategories:[...c.subcategories,value]}:c));setNewSubs(a=>({...a,[id]:""}))}
  function deleteSub(cat:string,sub:string){setCategories(a=>a.map(c=>c.name===cat?{...c,subcategories:c.subcategories.filter(s=>s!==sub)}:c));setVideos(a=>a.map(v=>v.category===cat&&v.subcategory===sub?{...v,subcategory:""}:v))}
  return <main className="app-shell"><aside className="sidebar"><a className="brand" href="#top"><span>R</span><strong>ReelRecall</strong></a><nav className="side-menu"><p>Library</p><button className={category==="All"&&!favorites&&!showArchive?"active":""} onClick={()=>chooseCategory("All")}><span>All videos</span><b>{videos.filter(v=>v.status==="available").length}</b></button><button className={favorites?"active":""} onClick={()=>{setFavorites(true);setShowArchive(false);setExpandedCategory("");setCategory("All");setSubcategory("")}}><span>♥ Favorites</span><b>{videos.filter(v=>v.favorite&&v.status==="available").length}</b></button><button className={showArchive?"active":""} onClick={()=>{setShowArchive(true);setFavorites(false);setExpandedCategory("");setCategory("All");setSubcategory("")}}><span>▣ Archive</span><b>{videos.filter(v=>v.status==="unavailable").length}</b></button><div className="menu-divider"/>{categories.map(c=><div className="menu-group" key={c.id}><button className={category===c.name&&!favorites&&!showArchive?"active":""} onClick={()=>chooseCategory(c.name)} aria-expanded={expandedCategory===c.name}><span>{c.name}</span><b>{videos.filter(v=>v.category===c.name&&v.status==="available").length}</b></button>{expandedCategory===c.name&&c.subcategories.length?<div className="submenu">{c.subcategories.map(s=><button key={s} className={subcategory===s?"active":""} onClick={()=>setSubcategory(s)}>{s}</button>)}</div>:null}</div>)}<button className="manage-link" onClick={()=>setManagerOpen(true)}>⚙ Manage categories</button></nav></aside><div className="app-content"><header><div className="header-actions"><button className="quiet" onClick={()=>void autoCategorize(videos.filter(v=>v.status==="available"))} disabled={aiRunning}>{aiRunning?"Organizing…":"✦ Auto-organize"}</button><button className="quiet" onClick={exportBackup} disabled={!videos.length}>Export backup</button><button className="quiet" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});location.href="/sign-in"}}>Sign out</button><button className="primary" onClick={openNew}>＋ Add video</button></div></header>
  <section className="intro compact-intro" id="top"><div><p className="kicker">REELRECALL</p><h1>Save it. <em>Find it.</em></h1></div><div className="import-panel"><span className="import-icon">↥</span><div><strong>Import from WhatsApp</strong><small>New videos are categorized and tagged automatically. Re-imports preserve your corrections.</small></div><button onClick={()=>fileRef.current?.click()}>Choose file</button><input ref={fileRef} type="file" accept=".txt,.json" onChange={importFile} hidden/></div></section><section className="toolbar"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search videos, notes, or tags"/></label></section><section className="results-head"><h2>{showArchive?"Archive":favorites?"Favorite videos":subcategory||category==="All"?subcategory||"All videos":category}</h2><span>{filtered.length} {filtered.length===1?"video":"videos"} · newest first</span></section>
  {!ready?<div className="empty">Loading…</div>:filtered.length?<section className="grid">{filtered.map(v=><VideoCard key={v.id} video={v} playing={playingId===v.id} onPlay={()=>setPlayingId(v.id)} onEdit={()=>openEdit(v)} onDelete={()=>setVideos(a=>a.filter(x=>x.id!==v.id))} onFavorite={()=>setVideos(a=>a.map(x=>x.id===v.id?{...x,favorite:!x.favorite}:x))} onStatus={()=>{setPlayingId(null);setVideos(a=>a.map(x=>x.id===v.id?{...x,status:x.status==="available"?"unavailable":"available"}:x));setToast(v.status==="available"?"Moved to Archive":"Restored to library")}}/>)}</section>:<section className="empty"><div>🎬</div><h2>{showArchive?"Archive is empty":videos.length?"No videos match":"Your ReelRecall library is ready"}</h2><p>{showArchive?"Videos marked unavailable will appear here.":"Import your WhatsApp chat to collect supported video links."}</p></section>}
  {dialogOpen?<div className="dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDialogOpen(false)}}><div className="dialog"><button className="dialog-close" onClick={()=>setDialogOpen(false)}>×</button><p className="kicker">VIDEO DETAILS</p><h2>{editingId?"Edit video":"Add a video"}</h2><form onSubmit={saveVideo}><label>Video URL<input type="url" required value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/></label><label>Video name<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="form-row"><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value,subcategory:""})}>{categories.map(c=><option key={c.id}>{c.name}</option>)}</select></label><label>Subcategory<select value={form.subcategory} onChange={e=>setForm({...form,subcategory:e.target.value})}><option value="">No subcategory</option>{formSubs.map(s=><option key={s}>{s}</option>)}</select></label></div><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Status})}><option value="available">Available</option><option value="unavailable">Not available</option></select></label><label>Tags<input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/></label><label>Notes<textarea rows={4} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary full">Save</button></form></div></div>:null}
  {managerOpen?<div className="dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setManagerOpen(false)}}><div className="dialog category-manager"><button className="dialog-close" onClick={()=>setManagerOpen(false)}>×</button><p className="kicker">ORGANIZE YOUR LIBRARY</p><h2>Manage categories</h2><div className="add-category"><input value={newCategory} onChange={e=>setNewCategory(e.target.value)} placeholder="New category"/><button className="primary" onClick={addCategory}>Add</button></div><div className="category-list">{categories.map(c=><section key={c.id}><div className="category-name"><input defaultValue={c.name} disabled={c.name==="Uncategorized"} onBlur={e=>renameCategory(c.id,e.target.value)}/>{c.name!=="Uncategorized"?<button className="danger" onClick={()=>deleteCategory(c.id)}>Delete</button>:null}</div><div className="subcategory-list">{c.subcategories.map(s=><span key={s}>{s}<button onClick={()=>deleteSub(c.name,s)}>×</button></span>)}</div><div className="add-sub"><input value={newSubs[c.id]??""} onChange={e=>setNewSubs({...newSubs,[c.id]:e.target.value})} placeholder="Add subcategory"/><button onClick={()=>addSub(c.id)}>Add</button></div></section>)}</div></div></div>:null}{toast?<div className="toast">{toast}</div>:null}</div></main>
}
