"use client";

import Image from "next/image";
import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from "react";

type Source = "Instagram" | "Facebook" | "YouTube" | "Other";
type Status = "available" | "unavailable";
type Recipe = { title:string; ingredients:string[]; steps:string[]; notes:string; servings:string; prepTime:string; extractedAt:string; source?:"description"|"video"; evidence?:string[]; };
type Video = { id:string; title:string; url:string; category:string; subcategory:string; tags:string[]; notes:string; favorite:boolean; source:Source; addedAt:string; status:Status; titleLocked:boolean; categoryLocked:boolean; tagsLocked:boolean; aiStatus:"pending"|"done"|"failed"; recipe?:Recipe|null };
type VideoForm = { title:string; url:string; category:string; subcategory:string; tags:string; notes:string; status:Status };
type Category = { id:string; name:string; subcategories:string[] };

const STORAGE_KEY="recipe-reel-library:v1", CATEGORY_KEY="video-library:categories:v1";
const URL_REGEX=/https?:\/\/(?:www\.)?(?:instagram\.com\/(?:reel|reels|p)\/[^\s<>]+|(?:m\.)?facebook\.com\/(?:reel|watch|share\/(?:r|v))\/[^\s<>]+|fb\.watch\/[^\s<>]+|youtube\.com\/(?:shorts\/[^\s<>]+|watch\?[^\s<>]+)|youtu\.be\/[^\s<>]+)/gi;
const DEFAULT_CATEGORIES:Category[]=[
  {id:"food",name:"Food",subcategories:["Breakfast","Entree","Snacks","Drinks","Dessert","Sides","Soups & Salads"]},
  {id:"travel",name:"Travel",subcategories:["Places","Travel Tips","Hotels & Stays"]},
  {id:"gardening",name:"Gardening",subcategories:["Plants","Landscaping","Gardening Tips"]},
  {id:"life",name:"Life Lessons",subcategories:["Motivation","Relationships","Spiritual"]},
  {id:"other",name:"Other",subcategories:[]},{id:"uncategorized",name:"Uncategorized",subcategories:[]}
];
const EMPTY_FORM:VideoForm={title:"",url:"",category:"Uncategorized",subcategory:"",tags:"",notes:"",status:"available"};

function cleanUrl(url:string){return url.replace(/[)>\],.!?]+$/,"")}
function isGenericTitle(raw:string){const title=raw.replace(/\u202f/g," ").replace(/\s+/g," ").trim(),words=title.split(/\s+/).filter(Boolean);return!title||/https?:\/\/|www\.|facebook\.com|instagram\.com|youtu(?:be\.com|\.be)/i.test(title)||/^(?:facebook|instagram|youtube|whatsapp|social media|other)(?:\s+(?:post|short|video|reel)(?:\s+\d+)?)?$/i.test(title)||/^(?:shared|saved|forwarded|new)\s+(?:post|short|video|reel)(?:\s+\d+)?$/i.test(title)||/^\[?\d{1,2}\/\d{1,2}\/\d{2,4},?\s+\d{1,2}:\d{2}(?::\d{2})?\s*(?:am|pm)?/i.test(title)||/^[\p{L} .'-]{1,40}:$/u.test(title)||/^#(?:[\p{L}\p{N}_-]+\s*)+$/u.test(title)||/\.(?:mp4|mov|m4v|webm)$/i.test(title)||title.length>100||words.length>14}
function canonicalUrl(raw:string){try{const u=new URL(cleanUrl(raw));u.hostname=u.hostname.replace(/^www\./,"").toLowerCase();if(u.hostname==="m.facebook.com")u.hostname="facebook.com";u.hash="";["igsh","igshid","mibextid","utm_source","utm_medium","utm_campaign","utm_content","si","feature"].forEach(k=>u.searchParams.delete(k));u.searchParams.sort();if(u.hostname==="instagram.com")u.pathname=u.pathname.replace(/^\/reels\//,"/reel/");u.pathname=u.pathname.replace(/\/$/,"");return u.toString().replace(/\?$/,"")}catch{return cleanUrl(raw).toLowerCase()}}
function sourceFor(url:string):Source{if(url.includes("instagram.com"))return"Instagram";if(url.includes("facebook.com")||url.includes("fb.watch"))return"Facebook";if(url.includes("youtube.com")||url.includes("youtu.be"))return"YouTube";return"Other"}
function dateFromLine(line:string){const candidates=[line.match(/^\[([^\]]+)\]/)?.[1],line.match(/^(\d{1,2}\/\d{1,2}\/\d{2,4},?\s+\d{1,2}:\d{2}(?::\d{2})?\s*(?:AM|PM)?)/i)?.[1]].filter(Boolean) as string[];for(const value of candidates){const parsed=new Date(value.replace(/\u202f/g," "));if(!Number.isNaN(parsed.getTime()))return parsed.toISOString()}return new Date().toISOString()}
function extractVideos(text:string,existing:Video[]){const seen=new Set(existing.map(v=>canonicalUrl(v.url)));return[...text.matchAll(URL_REGEX)].flatMap((match,index)=>{const url=cleanUrl(match[0]),key=canonicalUrl(url);if(seen.has(key))return[];seen.add(key);const start=text.lastIndexOf("\n",match.index??0)+1,end=text.indexOf("\n",match.index??0),line=text.slice(start,end===-1?undefined:end),label=line.slice(0,line.indexOf(match[0])).replace(/^.*? - (?:You|Me):\s*/i,"").replace(/^\[[^\]]+\]\s*[^:]+:\s*/,"").replace(/^\d{1,2}\/\d{1,2}\/\d{2,4},?\s+\d{1,2}:\d{2}(?::\d{2})?\s*(?:AM|PM)?\s*-\s*[^:]+:\s*/i,"").trim(),source=sourceFor(url);return[{id:crypto.randomUUID(),title:label||`${source} video ${existing.length+index+1}`,url,category:"Uncategorized",subcategory:"",tags:[],notes:label,favorite:false,source,addedAt:dateFromLine(line),status:"available" as Status,titleLocked:false,categoryLocked:false,tagsLocked:false,aiStatus:"pending" as const}]})}
function normalizeStoredVideos(items:Partial<Video>[]){const foodSubs=DEFAULT_CATEGORIES[0].subcategories;return items.map(v=>{const legacyFood=foodSubs.includes(v.category??""),resolvedCategory=legacyFood?"Food":v.category??"Uncategorized",resolvedTags=v.tags??[],resolvedTitle=v.title??"";return({...v,title:resolvedTitle,category:resolvedCategory,subcategory:legacyFood?v.category??"":v.subcategory??"",tags:resolvedTags,status:v.status??"available",addedAt:v.addedAt??new Date().toISOString(),titleLocked:v.titleLocked??!isGenericTitle(resolvedTitle),categoryLocked:v.categoryLocked??resolvedCategory!=="Uncategorized",tagsLocked:v.tagsLocked??resolvedTags.length>0,aiStatus:v.aiStatus??"done",recipe:v.recipe??null}) as Video})}
async function sampleVideoFrames(file:File,count=10){const objectUrl=URL.createObjectURL(file),video=document.createElement("video");video.src=objectUrl;video.preload="metadata";video.muted=true;video.playsInline=true;await new Promise<void>((resolve,reject)=>{video.onloadedmetadata=()=>resolve();video.onerror=()=>reject(new Error("Video could not be opened"))});const duration=Number.isFinite(video.duration)&&video.duration>0?video.duration:1,canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");if(!ctx){URL.revokeObjectURL(objectUrl);throw new Error("Canvas unavailable")}const frames:string[]=[];for(let i=0;i<count;i++){const time=Math.max(0,Math.min(Math.max(0,duration-.05),duration*((i+.5)/count)));await new Promise<void>((resolve,reject)=>{const done=()=>{cleanup();resolve()},bad=()=>{cleanup();reject(new Error("Could not read video frame"))},cleanup=()=>{video.removeEventListener("seeked",done);video.removeEventListener("error",bad)};video.addEventListener("seeked",done,{once:true});video.addEventListener("error",bad,{once:true});video.currentTime=time});const scale=Math.min(1,768/Math.max(video.videoWidth||1,video.videoHeight||1)),width=Math.max(1,Math.round((video.videoWidth||1)*scale)),height=Math.max(1,Math.round((video.videoHeight||1)*scale));canvas.width=width;canvas.height=height;ctx.drawImage(video,0,0,width,height);frames.push(canvas.toDataURL("image/jpeg",.7))}URL.revokeObjectURL(objectUrl);return frames}
function recipeText(video:Video){const r=video.recipe;if(!r)return"";return[r.title,r.servings?`Servings: ${r.servings}`:"",r.prepTime?`Time: ${r.prepTime}`:"","Ingredients",...r.ingredients.map(x=>`• ${x}`),"","Steps",...r.steps.map((x,i)=>`${i+1}. ${x}`),r.notes?`\nNotes\n${r.notes}`:"",`\nSource: ${video.url}`].filter(Boolean).join("\n")}
function youtubeId(raw:string){try{const u=new URL(raw);if(u.hostname.includes("youtu.be"))return u.pathname.split("/").filter(Boolean)[0];if(u.pathname.startsWith("/shorts/"))return u.pathname.split("/")[2];return u.searchParams.get("v")}catch{return null}}
function embedUrl(video:Video){if(video.source==="YouTube"){const id=youtubeId(video.url);return id?`https://www.youtube.com/embed/${id}?autoplay=1&rel=0`:null}if(video.source==="Instagram"){try{const u=new URL(video.url),p=u.pathname.split("/").filter(Boolean);return p[1]?`https://www.instagram.com/reel/${p[1]}/embed/`:null}catch{return null}}return null}

function InstagramEmbed({url,title}:{url:string;title:string}){
  const[html,setHtml]=useState(""),[ready,setReady]=useState(false);const containerRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{let active=true;setReady(false);fetch(`/api/embed?url=${encodeURIComponent(url)}`).then(r=>r.ok?r.json():Promise.reject()).then((data:{html?:string})=>{if(active&&data.html)setHtml(data.html)}).catch(()=>{if(active)setHtml("")});return()=>{active=false}},[url]);
  useEffect(()=>{if(!html)return;const process=()=>{const api=(window as Window&{instgrm?:{Embeds:{process:()=>void}}}).instgrm;if(api){api.Embeds.process()}};const markReady=()=>{if(containerRef.current?.querySelector("iframe"))setReady(true)};const observer=new MutationObserver(markReady);if(containerRef.current)observer.observe(containerRef.current,{childList:true,subtree:true});const existing=document.querySelector<HTMLScriptElement>('script[src="https://www.instagram.com/embed.js"]');if((window as Window&{instgrm?:unknown}).instgrm){process()}else if(existing){existing.addEventListener("load",process,{once:true})}else{const script=document.createElement("script");script.async=true;script.src="https://www.instagram.com/embed.js";script.addEventListener("load",process,{once:true});document.body.appendChild(script)}const retry=window.setTimeout(()=>{process();markReady()},500);return()=>{observer.disconnect();window.clearTimeout(retry);existing?.removeEventListener("load",process)}},[html]);
  return <div ref={containerRef} className={`instagram-player ${ready?"ready":"processing"}`} aria-label={title}>{html?<div dangerouslySetInnerHTML={{__html:html}}/>:<div className="embed-loading">Loading Instagram video…</div>}{html&&!ready?<div className="embed-shield">Preparing inline player…</div>:null}</div>
}

function FacebookEmbed({url,title,thumbnail,onThumbnailError}:{url:string;title:string;thumbnail:string|null;onThumbnailError:()=>void}){
  const[html,setHtml]=useState<string|null>(null),[ready,setReady]=useState(false),[fallback,setFallback]=useState(false);const containerRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{let active=true;setHtml(null);setReady(false);setFallback(false);fetch(`/api/facebook-embed?url=${encodeURIComponent(url)}`).then(async r=>{if(!r.ok)throw new Error("Embed unavailable");return r.json() as Promise<{html?:string}>}).then(data=>{if(active&&data.html)setHtml(data.html);else if(active)setFallback(true)}).catch(()=>{if(active)setFallback(true)});return()=>{active=false}},[url]);
  useEffect(()=>{if(!html||fallback)return;const markReady=()=>{if(containerRef.current?.querySelector("iframe"))setReady(true)};const process=()=>{markReady();const api=(window as Window&{FB?:{XFBML?:{parse:(root?:HTMLElement)=>void}}}).FB;api?.XFBML?.parse(containerRef.current??undefined)};const observer=new MutationObserver(markReady);if(containerRef.current)observer.observe(containerRef.current,{childList:true,subtree:true});markReady();const existing=document.querySelector<HTMLScriptElement>('script[data-reelrecall-facebook-sdk="true"]');const onLoad=()=>process();if((window as Window&{FB?:unknown}).FB){process()}else if(existing){existing.addEventListener("load",onLoad,{once:true})}else{const script=document.createElement("script");script.async=true;script.defer=true;script.crossOrigin="anonymous";script.dataset.reelrecallFacebookSdk="true";script.src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v25.0";script.addEventListener("load",onLoad,{once:true});document.body.appendChild(script)}const retry=window.setTimeout(process,500),giveUp=window.setTimeout(()=>{if(!containerRef.current?.querySelector("iframe"))setFallback(true)},7000);return()=>{observer.disconnect();window.clearTimeout(retry);window.clearTimeout(giveUp);existing?.removeEventListener("load",onLoad)}},[html,fallback]);
  if(fallback)return <div className={`facebook-fallback ${thumbnail?"has-thumbnail":""}`}>{thumbnail?<img src={thumbnail} alt="" onError={onThumbnailError}/>:null}<div className="facebook-fallback-copy"><strong>This reel can’t be played inline.</strong><small>It may require Facebook login or have audience or embedding restrictions.</small><a href={url} target="_blank" rel="noreferrer">Watch in Facebook ↗</a></div></div>;
  return <div ref={containerRef} className={`facebook-player ${ready?"ready":"processing"}`} aria-label={title}>{html?<div dangerouslySetInnerHTML={{__html:html}}/>:<div className="embed-loading">Checking Facebook playback…</div>}{html&&!ready?<div className="embed-shield">Preparing Facebook player…</div>:null}</div>
}

function VideoCard({video,playing,onPlay,onEdit,onDelete,onFavorite,onStatus,onRecipe,recipeLoading,onAnalyzeVideo,videoAnalyzing}:{video:Video;playing:boolean;onPlay:()=>void;onEdit:()=>void;onDelete:()=>void;onFavorite:()=>void;onStatus:()=>void;onRecipe:()=>void;recipeLoading:boolean;onAnalyzeVideo:()=>void;videoAnalyzing:boolean}){
  const[thumbnail,setThumbnail]=useState<string|null>(null),[failed,setFailed]=useState(false);
  useEffect(()=>{let active=true;setThumbnail(null);setFailed(false);fetch(`/api/thumbnail?url=${encodeURIComponent(video.url)}`).then(r=>r.ok?r.json():Promise.reject()).then((d:{thumbnail?:string})=>{if(active&&d.thumbnail)setThumbnail(d.thumbnail)}).catch(()=>{if(active)setFailed(true)});return()=>{active=false}},[video.url]);
  const player=embedUrl(video),unavailable=video.status==="unavailable",watchLabel=video.source==="Facebook"?"Watch in Facebook ↗":"Open original ↗";
  return <article className={`recipe-card ${unavailable?"unavailable":""}`}><div className={`source-badge ${video.source.toLowerCase()}`}>{video.source}</div><button className={`heart ${video.favorite?"active":""}`} onClick={onFavorite}>♥</button>
    {unavailable?<div className="not-available"><span>{video.source==="Facebook"?"This reel may no longer be available":"Video marked unavailable"}</span><small>{video.source==="Facebook"?"You marked this item unavailable. Open Facebook to verify its current state.":"You marked this item unavailable."}</small>{video.source==="Facebook"?<a href={video.url} target="_blank" rel="noreferrer">Watch in Facebook ↗</a>:null}</div>:playing&&video.source==="Facebook"?<FacebookEmbed url={video.url} title={video.title} thumbnail={thumbnail&&!failed?thumbnail:null} onThumbnailError={()=>setFailed(true)}/>:playing&&video.source==="Instagram"?<InstagramEmbed url={video.url} title={video.title}/>:playing&&player?<div className="inline-player"><iframe src={player} title={video.title} allow="autoplay; encrypted-media; picture-in-picture; web-share" allowFullScreen/></div>:<button className="reel-art" onClick={onPlay} aria-label={`Play ${video.title}`}>{thumbnail&&!failed?<img src={thumbnail} alt="" onError={()=>setFailed(true)}/>:<span className="plate">{video.category==="Travel"?"✈️":video.category==="Gardening"?"🌿":video.category==="Life Lessons"?"💡":video.category==="Food"?"🍲":"🎬"}</span>}<span className="play">▶</span></button>}
    <div className="card-body"><p className="eyebrow">{video.category}{video.subcategory?` · ${video.subcategory}`:""}</p><h2>{video.title}</h2><p className="saved-date">Saved {new Date(video.addedAt).toLocaleString()}</p>{video.tags.length?<div className="tags">{video.tags.map(t=><span key={t}>{t}</span>)}</div>:null}{video.notes?<p className="notes">{video.notes}</p>:<p className="notes muted">Add a note about this video.</p>}<div className="card-actions">{video.category==="Food"&&!video.recipe?<button className="recipe-action video-analysis" onClick={onAnalyzeVideo} disabled={videoAnalyzing}>{videoAnalyzing?"Analyzing…":"🎥 Analyze Video"}</button>:null}{video.category==="Food"?<button className="recipe-action" onClick={onRecipe} disabled={recipeLoading}>{recipeLoading?"Getting recipe…":"🍳 Recipe"}</button>:null}<a href={video.url} target="_blank" rel="noreferrer" className="watch">{watchLabel}</a><button onClick={onEdit}>Edit</button><button onClick={onStatus}>{unavailable?"Restore":"Mark unavailable"}</button><button className="delete" onClick={onDelete}>Delete</button></div></div></article>
}

export default function Home(){
  const[videoAnalysisId,setVideoAnalysisId]=useState<string|null>(null),[videoAnalysisBusy,setVideoAnalysisBusy]=useState(false),[videoAnalysisStage,setVideoAnalysisStage]=useState("");
  const[recipeVideoId,setRecipeVideoId]=useState<string|null>(null),[recipeLoadingId,setRecipeLoadingId]=useState<string|null>(null),[recipePasteVideoId,setRecipePasteVideoId]=useState<string|null>(null),[recipePasteText,setRecipePasteText]=useState("");
  const[videos,setVideos]=useState<Video[]>([]),[categories,setCategories]=useState<Category[]>(DEFAULT_CATEGORIES),[ready,setReady]=useState(false),[query,setQuery]=useState(""),[category,setCategory]=useState("All"),[expandedCategory,setExpandedCategory]=useState(""),[subcategory,setSubcategory]=useState(""),[favorites,setFavorites]=useState(false),[showArchive,setShowArchive]=useState(false),[form,setForm]=useState<VideoForm>(EMPTY_FORM),[editingId,setEditingId]=useState<string|null>(null),[dialogOpen,setDialogOpen]=useState(false),[managerOpen,setManagerOpen]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[clearStep,setClearStep]=useState<0|1|2>(0),[newCategory,setNewCategory]=useState(""),[newSubs,setNewSubs]=useState<Record<string,string>>({}),[playingId,setPlayingId]=useState<string|null>(null),[aiRunning,setAiRunning]=useState(false),[aiProgress,setAiProgress]=useState(""),[toast,setToast]=useState("");const fileRef=useRef<HTMLInputElement>(null),shareHandledRef=useRef(false),aiRunRef=useRef(false);
  useEffect(()=>{let active=true;(async()=>{let localVideos:Video[]=[],localCategories:Category[]=DEFAULT_CATEGORIES;try{const saved=localStorage.getItem(STORAGE_KEY),savedCats=localStorage.getItem(CATEGORY_KEY);if(saved)localVideos=normalizeStoredVideos(JSON.parse(saved));if(savedCats)localCategories=JSON.parse(savedCats)}catch{}try{const response=await fetch("/api/library",{cache:"no-store"});if(response.status===401){location.href="/sign-in";return}if(!response.ok)throw new Error();const result=await response.json() as {exists:boolean;data?:{videos?:Partial<Video>[];categories?:Category[]}};if(!active)return;if(result.exists&&result.data){setVideos(normalizeStoredVideos(result.data.videos??[]));setCategories(result.data.categories?.length?result.data.categories:DEFAULT_CATEGORIES)}else{setVideos(localVideos);setCategories(localCategories);if(localVideos.length||localCategories.length)await fetch("/api/library",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({videos:localVideos,categories:localCategories})})}}catch{if(active){setVideos(localVideos);setCategories(localCategories);setToast("Database unavailable—using the local cache")}}finally{if(active)setReady(true)}})();return()=>{active=false}},[]);
  useEffect(()=>{if(!ready)return;localStorage.setItem(STORAGE_KEY,JSON.stringify(videos));localStorage.setItem(CATEGORY_KEY,JSON.stringify(categories));const timer=window.setTimeout(()=>{fetch("/api/library",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({videos,categories})}).then(response=>{if(response.status===401)location.href="/sign-in"}).catch(()=>{})},500);return()=>window.clearTimeout(timer)},[videos,categories,ready]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),3200);return()=>clearTimeout(t)},[toast]);
  useEffect(()=>{if(!ready||shareHandledRef.current)return;const params=new URLSearchParams(window.location.search),sharedUrl=params.get("shared"),shareError=params.get("shareError");if(!sharedUrl&&!shareError)return;shareHandledRef.current=true;window.history.replaceState(null,"",window.location.pathname);if(shareError){setToast("No supported reel link was found in that share");return}const url=cleanUrl(sharedUrl??"");if(!url)return;if(videos.some(v=>canonicalUrl(v.url)===canonicalUrl(url))){setToast("That reel is already in your library");return}const source=sourceFor(url),rawTitle=(params.get("shareTitle")??"").replace(/\s+/g," ").trim(),rawText=(params.get("shareText")??"").trim(),title=rawTitle&&!rawTitle.includes(url)?rawTitle.slice(0,180):`${source} reel`,notes=rawText.replace(url,"").trim().slice(0,600),video:Video={id:crypto.randomUUID(),title,url,category:"Uncategorized",subcategory:"",tags:[],notes,favorite:false,source,addedAt:new Date().toISOString(),status:"available",titleLocked:false,categoryLocked:false,tagsLocked:false,aiStatus:"pending"};setVideos(current=>[video,...current]);setToast(`${source} reel added from Share. Organizing…`);void autoCategorize([video])},[ready,videos]);
  useEffect(()=>{if(!ready||aiRunning)return;const pending=videos.filter(v=>v.aiStatus==="pending");if(pending.length)void autoCategorize(pending)},[ready,videos,aiRunning]);
  useEffect(()=>{if(!ready)return;let refreshing=false;const refreshSharedVideos=async()=>{if(refreshing||document.visibilityState!=="visible")return;refreshing=true;try{const response=await fetch("/api/library",{cache:"no-store"});if(response.status===401){location.href="/sign-in";return}if(!response.ok)return;const result=await response.json() as {exists:boolean;data?:{videos?:Partial<Video>[];categories?:Category[]}};if(result.exists&&result.data){setVideos(normalizeStoredVideos(result.data.videos??[]));if(result.data.categories?.length)setCategories(result.data.categories)}}finally{refreshing=false}};const onVisible=()=>{if(document.visibilityState==="visible")void refreshSharedVideos()};document.addEventListener("visibilitychange",onVisible);window.addEventListener("focus",onVisible);void refreshSharedVideos();return()=>{document.removeEventListener("visibilitychange",onVisible);window.removeEventListener("focus",onVisible)}},[ready]);
  const formSubs=categories.find(c=>c.name===form.category)?.subcategories??[],filtered=useMemo(()=>{const q=query.toLowerCase().trim();return videos.filter(v=>(showArchive?v.status==="unavailable":v.status==="available")&&(!q||[v.title,v.category,v.subcategory,v.notes,...v.tags,...(v.recipe?.ingredients??[]),...(v.recipe?.steps??[])].join(" ").toLowerCase().includes(q))&&(category==="All"||v.category===category)&&(!subcategory||v.subcategory===subcategory)&&(!favorites||v.favorite)).sort((a,b)=>new Date(b.addedAt).getTime()-new Date(a.addedAt).getTime())},[videos,query,category,subcategory,favorites,showArchive]);
  const chooseCategory=(name:string)=>{setCategory(name);setExpandedCategory(current=>name==="All"?"":current===name?"":name);setSubcategory("");setFavorites(false);setShowArchive(false);setPlayingId(null)},openNew=()=>{setEditingId(null);setForm(EMPTY_FORM);setDialogOpen(true)},openEdit=(v:Video)=>{setEditingId(v.id);setForm({title:v.title,url:v.url,category:v.category,subcategory:v.subcategory,tags:v.tags.join(", "),notes:v.notes,status:v.status});setDialogOpen(true)};
  function saveVideo(e:FormEvent){e.preventDefault();const url=cleanUrl(form.url.trim()),tags=form.tags.split(",").map(t=>t.trim()).filter(Boolean);if(editingId){setVideos(a=>a.map(v=>v.id===editingId?{...v,...form,url,tags,source:sourceFor(url),titleLocked:v.titleLocked||form.title.trim()!==v.title,categoryLocked:true,tagsLocked:true}:v));setToast("Video updated and manual choices locked")}else{if(videos.some(v=>canonicalUrl(v.url)===canonicalUrl(url))){setToast("That video is already in your library");return}setVideos(a=>[{id:crypto.randomUUID(),...form,url,tags,source:sourceFor(url),favorite:false,addedAt:new Date().toISOString(),titleLocked:true,categoryLocked:true,tagsLocked:true,aiStatus:"done"},...a]);setToast("Video added")}setDialogOpen(false)}
  async function autoCategorize(items:Video[]){if(aiRunRef.current)return;const eligible=items.filter(v=>v.status==="available"&&((v.aiStatus==="pending"||v.aiStatus==="failed")&&(!v.categoryLocked||!v.tagsLocked||!v.titleLocked)||(!v.titleLocked&&isGenericTitle(v.title))));if(!eligible.length){setToast("No videos need AI organization");return}aiRunRef.current=true;setAiRunning(true);let completed=0,failed=0,processed=0;for(let start=0;start<eligible.length;start+=3){const batch=eligible.slice(start,start+3);await Promise.all(batch.map(async video=>{try{const response=await fetch("/api/classify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({video:{url:video.url,title:video.title,notes:video.notes},categories})});if(!response.ok)throw new Error();const suggestion=await response.json() as {title?:string;description?:string;category:string;subcategory:string;tags:string[]};setVideos(current=>current.map(item=>{if(item.id!==video.id)return item;const title=suggestion.title?.trim(),titleOnly=video.aiStatus==="done";return{...item,title:!item.titleLocked&&isGenericTitle(item.title)&&title&&!isGenericTitle(title)?title:item.title,notes:item.notes||suggestion.description||item.notes,category:titleOnly||item.categoryLocked?item.category:suggestion.category,subcategory:titleOnly||item.categoryLocked?item.subcategory:suggestion.subcategory,tags:titleOnly||item.tagsLocked?item.tags:suggestion.tags,aiStatus:"done"}}));completed++}catch{failed++;setVideos(current=>current.map(item=>item.id===video.id?{...item,aiStatus:video.aiStatus==="done"?"done":"failed"}:item))}finally{processed++;setAiProgress(`${processed}/${eligible.length}`)}}))}aiRunRef.current=false;setAiRunning(false);setAiProgress("");setToast(completed?`AI updated ${completed} video${completed===1?"":"s"}${failed?`; ${failed} could not be updated`:""}`:"AI title generation is unavailable. Check the API key.")}
  async function importFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{if(file.name.toLowerCase().endsWith(".json")){const seen=new Set(videos.map(v=>canonicalUrl(v.url))),unique=(JSON.parse(await file.text()) as Video[]).filter(v=>v.url&&!seen.has(canonicalUrl(v.url))).map(v=>({...v,subcategory:v.subcategory??"",status:v.status??"available" as Status,categoryLocked:v.categoryLocked??true,tagsLocked:v.tagsLocked??true,aiStatus:v.aiStatus??"done" as const}));setVideos(a=>[...unique,...a]);setToast(`Imported ${unique.length} videos from backup`)}else{const added=extractVideos(await file.text(),videos);setVideos(a=>[...added,...a]);setToast(added.length?`Imported ${added.length} new links. Organizing…`:"No new links—duplicates and prior corrections were preserved");if(added.length)void autoCategorize(added)} }catch{setToast("Could not read that file")}e.target.value=""}
  async function extractRecipe(video:Video){if(video.recipe){setRecipeVideoId(video.id);return}setRecipeLoadingId(video.id);try{const response=await fetch("/api/recipe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({video:{url:video.url,title:video.title,notes:video.notes}})});if(!response.ok)throw new Error();const result=await response.json() as {recipe:Recipe|null;descriptionFound?:boolean;facebookBlocked?:boolean};if(!result.recipe){if(video.source==="Facebook"){setRecipePasteVideoId(video.id);setRecipePasteText("");setToast(result.descriptionFound?"Facebook exposed some text, but not enough recipe detail":"Facebook did not expose the reel description to ReelRecall")}else setToast(result.descriptionFound?"The reel description does not contain enough recipe detail":"No usable recipe description was available for this reel");return}setVideos(current=>current.map(item=>item.id===video.id?{...item,recipe:result.recipe}:item));setRecipeVideoId(video.id);setToast("Recipe extracted and saved")}catch{setToast("Recipe extraction is unavailable. Check the OpenAI API configuration")}finally{setRecipeLoadingId(null)}}
  async function extractPastedRecipe(){const video=recipePasteVideoId?videos.find(v=>v.id===recipePasteVideoId):null;if(!video||!recipePasteText.trim())return;setRecipeLoadingId(video.id);try{const response=await fetch("/api/recipe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({video:{url:video.url,title:video.title,notes:video.notes},description:recipePasteText.trim()})});if(!response.ok)throw new Error();const result=await response.json() as {recipe:Recipe|null};if(!result.recipe){setToast("The pasted description still does not contain enough recipe detail");return}setVideos(current=>current.map(item=>item.id===video.id?{...item,recipe:result.recipe}:item));setRecipePasteVideoId(null);setRecipePasteText("");setRecipeVideoId(video.id);setToast("Recipe extracted and saved")}catch{setToast("Recipe extraction is unavailable. Check the OpenAI API configuration")}finally{setRecipeLoadingId(null)}}
  async function refreshRecipe(video:Video){setRecipeLoadingId(video.id);try{const response=await fetch("/api/recipe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({video:{url:video.url,title:video.title,notes:video.notes}})});if(!response.ok)throw new Error();const result=await response.json() as {recipe:Recipe|null;descriptionFound?:boolean};if(!result.recipe){setToast(result.descriptionFound?"The reel description does not contain enough recipe detail":"No usable recipe description was available for this reel");return}setVideos(current=>current.map(item=>item.id===video.id?{...item,recipe:result.recipe}:item));setToast("Recipe refreshed")}catch{setToast("Recipe extraction is unavailable. Check the OpenAI API configuration")}finally{setRecipeLoadingId(null)}}
  async function copyRecipe(video:Video){const text=recipeText(video);if(!text)return;try{await navigator.clipboard.writeText(text);setToast("Recipe copied")}catch{setToast("Could not copy recipe")}}
  async function analyzeReelVideo(video:Video){if(video.source!=="Facebook"&&video.source!=="Instagram"){setToast("Direct AI video analysis currently supports Facebook and Instagram reels");return}setVideoAnalysisId(video.id);setVideoAnalysisBusy(true);setVideoAnalysisStage("Retrieving public reel…");try{const response=await fetch("/api/reel-video-recipe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({video:{url:video.url,title:video.title,notes:video.notes,source:video.source}})});const result=await response.json() as {recipe:Recipe|null;message?:string;error?:string};if(!response.ok)throw new Error(result.error||result.message||"Reel analysis failed");if(!result.recipe){setToast(result.message||"AI could not identify enough recipe detail in this reel");return}setVideos(current=>current.map(item=>item.id===video.id?{...item,recipe:result.recipe}:item));setRecipeVideoId(video.id);setToast("Recipe created from the reel video")}catch(error){setToast(error instanceof Error?error.message:"Reel analysis failed")}finally{setVideoAnalysisBusy(false);setVideoAnalysisStage("");setVideoAnalysisId(null)}}
  function exportBackup(){const blob=new Blob([JSON.stringify(videos,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`saved-video-library-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
  function addCategory(){const name=newCategory.trim();if(!name||categories.some(c=>c.name.toLowerCase()===name.toLowerCase()))return;setCategories(a=>[...a.slice(0,-1),{id:crypto.randomUUID(),name,subcategories:[]},a.at(-1)!]);setNewCategory("")}
  function renameCategory(id:string,name:string){const old=categories.find(c=>c.id===id)?.name;if(!old||!name.trim())return;setCategories(a=>a.map(c=>c.id===id?{...c,name:name.trim()}:c));setVideos(a=>a.map(v=>v.category===old?{...v,category:name.trim()}:v));if(category===old)setCategory(name.trim())}
  function deleteCategory(id:string){const c=categories.find(x=>x.id===id);if(!c||c.name==="Uncategorized"||!confirm(`Delete ${c.name}? Its videos will move to Uncategorized.`))return;setCategories(a=>a.filter(x=>x.id!==id));setVideos(a=>a.map(v=>v.category===c.name?{...v,category:"Uncategorized",subcategory:""}:v));chooseCategory("All")}
  function addSub(id:string){const value=(newSubs[id]??"").trim();if(!value)return;setCategories(a=>a.map(c=>c.id===id&&!c.subcategories.includes(value)?{...c,subcategories:[...c.subcategories,value]}:c));setNewSubs(a=>({...a,[id]:""}))}
  function deleteSub(cat:string,sub:string){setCategories(a=>a.map(c=>c.name===cat?{...c,subcategories:c.subcategories.filter(s=>s!==sub)}:c));setVideos(a=>a.map(v=>v.category===cat&&v.subcategory===sub?{...v,subcategory:""}:v))}
  async function clearAllVideos(){try{const response=await fetch("/api/library",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({videos:[],categories})});if(!response.ok)throw new Error();setVideos([]);localStorage.setItem(STORAGE_KEY,"[]");setPlayingId(null);setCategory("All");setSubcategory("");setFavorites(false);setShowArchive(false);setClearStep(0);setToast("All videos were cleared. Categories were preserved.")}catch{setToast("Could not clear the video library")}}
  const aiQueue=videos.filter(v=>v.status==="available"&&(((v.aiStatus==="pending"||v.aiStatus==="failed")&&(!v.categoryLocked||!v.tagsLocked||!v.titleLocked))||(!v.titleLocked&&isGenericTitle(v.title))));
  const recipeVideo=recipeVideoId?videos.find(v=>v.id===recipeVideoId)??null:null;
  return <main className="app-shell"><aside className="sidebar"><a className="brand" href="#top"><Image className="brand-logo" src="/icons/reelreplay-mark.png" alt="" width={42} height={42} priority/><strong>ReelRecall</strong></a><nav className="side-menu"><p>Library</p><button className={category==="All"&&!favorites&&!showArchive?"active":""} onClick={()=>chooseCategory("All")}><span>All videos</span><b>{videos.filter(v=>v.status==="available").length}</b></button><button className={favorites?"active":""} onClick={()=>{setFavorites(true);setShowArchive(false);setExpandedCategory("");setCategory("All");setSubcategory("")}}><span>♥ Favorites</span><b>{videos.filter(v=>v.favorite&&v.status==="available").length}</b></button><button className={showArchive?"active":""} onClick={()=>{setShowArchive(true);setFavorites(false);setExpandedCategory("");setCategory("All");setSubcategory("")}}><span>▣ Archive</span><b>{videos.filter(v=>v.status==="unavailable").length}</b></button><div className="menu-divider"/>{categories.map(c=><div className="menu-group" key={c.id}><button className={category===c.name&&!favorites&&!showArchive?"active":""} onClick={()=>chooseCategory(c.name)} aria-expanded={expandedCategory===c.name}><span>{c.name}</span><b>{videos.filter(v=>v.category===c.name&&v.status==="available").length}</b></button>{expandedCategory===c.name&&c.subcategories.length?<div className="submenu">{c.subcategories.map(s=><button key={s} className={subcategory===s?"active":""} onClick={()=>setSubcategory(s)}>{s}</button>)}</div>:null}</div>)}</nav><button className="settings-link" onClick={()=>setSettingsOpen(true)}>⚙ <span>Settings</span></button></aside><div className="app-content"><header><div className="header-actions"><button className="quiet" onClick={()=>void autoCategorize(aiQueue)} disabled={aiRunning||!aiQueue.length}>{aiRunning?`Organizing ${aiProgress}…`:aiQueue.length?`✦ AI Organize (${aiQueue.length})`:"✓ AI Organized"}</button><button className="quiet" onClick={exportBackup} disabled={!videos.length}>Export backup</button><button className="quiet" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});location.href="/sign-in"}}>Sign out</button><button className="primary" onClick={openNew}>＋ Add video</button></div></header>
  <section className="intro compact-intro" id="top"><div><p className="kicker">REELRECALL</p><h1>Save it. <em>Find it.</em></h1></div></section><section className="toolbar"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search videos, notes, or tags"/></label></section><section className="results-head"><h2>{showArchive?"Archive":favorites?"Favorite videos":subcategory||category==="All"?subcategory||"All videos":category}</h2><span>{filtered.length} {filtered.length===1?"video":"videos"} · newest first</span></section>
  {videoAnalysisBusy&&videoAnalysisId?<div className="video-analysis-banner"><span className="spinner"/><strong>{videoAnalysisStage||"Analyzing reel…"}</strong><small>ReelRecall is analyzing only the selected reel.</small></div>:null}
  {!ready?<div className="empty">Loading…</div>:filtered.length?<section className="grid">{filtered.map(v=><VideoCard key={v.id} video={v} playing={playingId===v.id} onPlay={()=>setPlayingId(v.id)} onEdit={()=>openEdit(v)} onDelete={()=>setVideos(a=>a.filter(x=>x.id!==v.id))} onFavorite={()=>setVideos(a=>a.map(x=>x.id===v.id?{...x,favorite:!x.favorite}:x))} onStatus={()=>{setPlayingId(null);setVideos(a=>a.map(x=>x.id===v.id?{...x,status:x.status==="available"?"unavailable":"available"}:x));setToast(v.status==="available"?"Moved to Archive":"Restored to library")}} onRecipe={()=>void extractRecipe(v)} recipeLoading={recipeLoadingId===v.id} onAnalyzeVideo={()=>void analyzeReelVideo(v)} videoAnalyzing={videoAnalysisBusy&&videoAnalysisId===v.id}/>)}</section>:<section className="empty"><div>🎬</div><h2>{showArchive?"Archive is empty":videos.length?"No videos match":"Your ReelRecall library is ready"}</h2><p>{showArchive?"Videos marked unavailable will appear here.":"Import your WhatsApp chat to collect supported video links."}</p></section>}
  {recipePasteVideoId?<div className="dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setRecipePasteVideoId(null)}}><div className="dialog facebook-recipe-paste"><button className="dialog-close" onClick={()=>setRecipePasteVideoId(null)}>×</button><p className="kicker">FACEBOOK RECIPE</p><h2>Paste the reel description</h2><p>Facebook is allowing the reel to play, but it did not expose the caption text to ReelRecall's server. Copy the recipe text from the Facebook reel description and paste it below.</p><textarea value={recipePasteText} onChange={e=>setRecipePasteText(e.target.value)} placeholder="Paste the Facebook reel description, ingredients and cooking steps here…" autoFocus/><div className="recipe-footer"><button type="button" className="primary" onClick={()=>void extractPastedRecipe()} disabled={!recipePasteText.trim()||recipeLoadingId===recipePasteVideoId}>{recipeLoadingId===recipePasteVideoId?"Extracting…":"Extract Recipe"}</button><button type="button" onClick={()=>setRecipePasteVideoId(null)}>Cancel</button>{recipePasteVideoId?(()=>{const v=videos.find(x=>x.id===recipePasteVideoId);return v?<a href={v.url} target="_blank" rel="noreferrer">Open Facebook ↗</a>:null})():null}</div></div></div>:null}
  {recipeVideo?.recipe?<div className="dialog-backdrop recipe-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setRecipeVideoId(null)}}><div className="dialog recipe-dialog"><button className="dialog-close" onClick={()=>setRecipeVideoId(null)}>×</button><p className="kicker">SAVED RECIPE</p><h2>{recipeVideo.recipe.title||recipeVideo.title}</h2>{recipeVideo.recipe.servings||recipeVideo.recipe.prepTime?<div className="recipe-meta">{recipeVideo.recipe.servings?<span>🍽 {recipeVideo.recipe.servings}</span>:null}{recipeVideo.recipe.prepTime?<span>⏱ {recipeVideo.recipe.prepTime}</span>:null}</div>:null}<section className="recipe-section"><h3>Ingredients</h3><ul>{recipeVideo.recipe.ingredients.map((item,index)=><li key={`${index}-${item}`}>{item}</li>)}</ul></section><section className="recipe-section"><h3>Steps</h3><ol>{recipeVideo.recipe.steps.map((step,index)=><li key={`${index}-${step}`}>{step}</li>)}</ol></section>{recipeVideo.recipe.notes?<section className="recipe-section recipe-notes"><h3>Notes</h3><p>{recipeVideo.recipe.notes}</p></section>:null}{recipeVideo.recipe.evidence?.length?<div className="recipe-evidence"><strong>AI used</strong>{recipeVideo.recipe.evidence.map(item=><span key={item}>{item}</span>)}</div>:null}<div className="recipe-footer"><button type="button" className="primary" onClick={()=>void copyRecipe(recipeVideo)}>Copy Recipe</button><button type="button" onClick={()=>void refreshRecipe(recipeVideo)} disabled={recipeLoadingId===recipeVideo.id}>{recipeLoadingId===recipeVideo.id?"Refreshing…":"Refresh from description"}</button><a href={recipeVideo.url} target="_blank" rel="noreferrer">Open original ↗</a></div><small className="recipe-disclaimer">{recipeVideo.recipe.source==="video"?"Generated from sampled video frames and available narration. Check the original reel when exact quantities or timing matter.":"Extracted from the saved/public reel description. Check the original reel when exact quantities or timing matter."}</small></div></div>:null}
  {dialogOpen?<div className="dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDialogOpen(false)}}><div className="dialog"><button className="dialog-close" onClick={()=>setDialogOpen(false)}>×</button><p className="kicker">VIDEO DETAILS</p><h2>{editingId?"Edit video":"Add a video"}</h2><form onSubmit={saveVideo}><label>Video URL<input type="url" required value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/></label><label>Video name<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="form-row"><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value,subcategory:""})}>{categories.map(c=><option key={c.id}>{c.name}</option>)}</select></label><label>Subcategory<select value={form.subcategory} onChange={e=>setForm({...form,subcategory:e.target.value})}><option value="">No subcategory</option>{formSubs.map(s=><option key={s}>{s}</option>)}</select></label></div><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Status})}><option value="available">Available</option><option value="unavailable">Not available</option></select></label><label>Tags<input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/></label><label>Notes<textarea rows={4} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary full">Save</button></form></div></div>:null}
  {settingsOpen?<div className="dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSettingsOpen(false)}}><div className="dialog settings-dialog"><button className="dialog-close" onClick={()=>setSettingsOpen(false)}>×</button><p className="kicker">REELRECALL SETTINGS</p><h2>Settings</h2><section className="settings-section"><div><strong>Import from WhatsApp</strong><p>Add new links without duplicating videos or overwriting your corrections.</p></div><button className="primary" onClick={()=>fileRef.current?.click()}>Choose chat file</button><input ref={fileRef} type="file" accept=".txt,.json" onChange={e=>{void importFile(e);setSettingsOpen(false)}} hidden/></section><section className="settings-section"><div><strong>Categories and subcategories</strong><p>Add, rename, or remove the menu categories used for your videos.</p></div><button className="settings-action" onClick={()=>{setSettingsOpen(false);setManagerOpen(true)}}>Manage</button></section><section className="settings-section danger-zone"><div><strong>Admin</strong><p>Clear every active and archived video. Categories and settings are preserved.</p></div><button className="danger-button" disabled={!videos.length} onClick={()=>{setSettingsOpen(false);setClearStep(1)}}>Clear all videos</button></section></div></div>:null}
  {clearStep===1?<div className="dialog-backdrop"><div className="dialog confirm-dialog"><p className="kicker">FIRST CONFIRMATION</p><h2>Clear all videos?</h2><p>This will remove all {videos.length} active and archived videos from ReelRecall.</p><div className="confirm-actions"><button className="settings-action" onClick={()=>setClearStep(0)}>Cancel</button><button className="danger-button" onClick={()=>setClearStep(2)}>Continue</button></div></div></div>:null}
  {clearStep===2?<div className="dialog-backdrop"><div className="dialog confirm-dialog"><p className="kicker">FINAL CONFIRMATION</p><h2>This cannot be undone</h2><p>Your categories will remain, but every saved video will be permanently removed from the database and local cache.</p><div className="confirm-actions"><button className="settings-action" onClick={()=>setClearStep(0)}>Keep my videos</button><button className="danger-button" onClick={()=>void clearAllVideos()}>Permanently clear all</button></div></div></div>:null}
  {managerOpen?<div className="dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setManagerOpen(false)}}><div className="dialog category-manager"><button className="dialog-close" onClick={()=>setManagerOpen(false)}>×</button><p className="kicker">ORGANIZE YOUR LIBRARY</p><h2>Manage categories</h2><div className="add-category"><input value={newCategory} onChange={e=>setNewCategory(e.target.value)} placeholder="New category"/><button className="primary" onClick={addCategory}>Add</button></div><div className="category-list">{categories.map(c=><section key={c.id}><div className="category-name"><input defaultValue={c.name} disabled={c.name==="Uncategorized"} onBlur={e=>renameCategory(c.id,e.target.value)}/>{c.name!=="Uncategorized"?<button className="danger" onClick={()=>deleteCategory(c.id)}>Delete</button>:null}</div><div className="subcategory-list">{c.subcategories.map(s=><span key={s}>{s}<button onClick={()=>deleteSub(c.name,s)}>×</button></span>)}</div><div className="add-sub"><input value={newSubs[c.id]??""} onChange={e=>setNewSubs({...newSubs,[c.id]:e.target.value})} placeholder="Add subcategory"/><button onClick={()=>addSub(c.id)}>Add</button></div></section>)}</div></div></div>:null}{toast?<div className="toast">{toast}</div>:null}</div></main>
}
